export const challenges = [
  {
    level: 1,
    title: "Print Hello",
    task: "Print 'Hello, World!'",
    hint: "Use dikhao with a string.",
    expectedOutput: `Hello, World!\n`,
  },
  {
    level: 2,
    title: "Print a Number",
    task: "Print the number 42.",
    hint: "Use dikhao with a number.",
    expectedOutput: `42\n`,
  },
  {
    level: 3,
    title: "Declare and Print Variable",
    task: "Declare a variable x with value 10 and print it.",
    hint: "Use banao and dikhao.",
    expectedOutput: `10\n`,
  },
  {
    level: 4,
    title: "Simple Addition",
    task: "Print the sum of 5 and 7.",
    hint: "Use dikhao with addition.",
    expectedOutput: `12\n`,
  },
  {
    level: 5,
    title: "String Concatenation",
    task: "Print 'Hello' and 'World' together.",
    hint: "Use + to join strings.",
    expectedOutput: `HelloWorld\n`,
  },
  {
    level: 6,
    title: "Print Array Element",
    task: "Print the first element of array [3, 6, 9].",
    hint: "Use array indexing.",
    expectedOutput: `3\n`,
  },
  {
    level: 7,
    title: "Simple Subtraction",
    task: "Print the result of 15 minus 4.",
    hint: "Use dikhao with subtraction.",
    expectedOutput: `11\n`,
  },
  {
    level: 8,
    title: "Declare and Print String",
    task: "Declare a variable msg with value 'Hi' and print it.",
    hint: "Use banao and dikhao.",
    expectedOutput: `Hi\n`,
  },
  {
    level: 9,
    title: "Simple Multiplication",
    task: "Print the product of 3 and 4.",
    hint: "Use dikhao with multiplication.",
    expectedOutput: `12\n`,
  },
  {
    level: 10,
    title: "Simple Division",
    task: "Print the result of 20 divided by 4.",
    hint: "Use dikhao with division.",
    expectedOutput: `5\n`,
  },
];

