export const challenges = [
  {
    level: 1,
    title: "Print Hello",
    task: "Print 'Hello, World!'",
    hint: "Use dikhao with a string.",
    expectedOutput: `Hello, World!\n`,
  },
  {
    level: 2,
    title: "Print a Number",
    task: "Print the number 42.",
    hint: "Use dikhao with a number.",
    expectedOutput: `42\n`,
  },
  {
    level: 3,
    title: "Declare and Print Variable",
    task: "Declare a variable x with value 10 and print it.",
    hint: "Use banao and dikhao.",
    expectedOutput: `10\n`,
  },
  {
    level: 4,
    title: "Simple Addition",
    task: "Print the sum of 5 and 7.",
    hint: "Use dikhao with addition.",
    expectedOutput: `12\n`,
  },
  {
    level: 5,
    title: "String Concatenation",
    task: "Print 'Hello' and 'World' together.",
    hint: "Use + to join strings.",
    expectedOutput: `HelloWorld\n`,
  },
  {
    level: 6,
    title: "Print Array Element",
    task: "Print the first element of array [3, 6, 9].",
    hint: "Use array indexing.",
    expectedOutput: `3\n`,
  },
  {
    level: 7,
    title: "Simple Subtraction",
    task: "Print the result of 15 minus 4.",
    hint: "Use dikhao with subtraction.",
    expectedOutput: `11\n`,
  },
  {
    level: 8,
    title: "Declare and Print String",
    task: "Declare a variable msg with value 'Hi' and print it.",
    hint: "Use banao and dikhao.",
    expectedOutput: `Hi\n`,
  },
  {
    level: 9,
    title: "Simple Multiplication",
    task: "Print the product of 3 and 4.",
    hint: "Use dikhao with multiplication.",
    expectedOutput: `12\n`,
  },
  {
    level: 10,
    title: "Simple Division",
    task: "Print the result of 20 divided by 4.",
    hint: "Use dikhao with division.",
    expectedOutput: `5\n`,
  },
  {
    level: 11,
    title: "Print Array Length",
    task: "Print the length of array [1, 2, 3, 4].",
    hint: "Use arr.length.",
    expectedOutput: `4\n`,
  },
  {
    level: 12,
    title: "Sum All Array Elements",
    task: "Print the sum of all elements in array [2, 4, 6, 8] using a loop.",
    hint: "Use jabtak to loop and sum.",
    expectedOutput: `20\n`,
  },
  {
    level: 13,
    title: "Find Maximum in Array",
    task: "Print the maximum value in array [7, 3, 9, 5].",
    hint: "Use a loop and comparison.",
    expectedOutput: `9\n`,
  },
  {
    level: 14,
    title: "Reverse a String",
    task: "Print the reverse of string 'hello'.",
    hint: "Use a loop from end to start.",
    expectedOutput: `olleh\n`,
  },
  {
    level: 15,
    title: "Find Smallest in Array",
    task: "Print the smallest value in array [8, 3, 6, 2].",
    hint: "Use a loop and comparison.",
    expectedOutput: `2\n`,
  },
];
